version: '3'

services:
  web:
    build:
      context: .
    command: gunicorn -w 4 -b 0.0.0.0:5000 wsgi:app
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: app_database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
