version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"

  web:
    build:
      dockerfile: docker-build/Dockerfile
      context: ./
    image: flask-app:latest
    ports:
      - "5000:5000"
    depends_on:
      - db