version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword

  web:
    build: .
    command: gunicorn -w 4 -b 127.0.0.1:8000 myapp:app
    volumes:
      - ./myapp:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - my_network

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    networks:
      - my_network

networks:
  my_network:
